
Finding the derivative of $x^3 + 2x^2 +3$
```{r}
evalD<- function(f,x){
h<- 1e-03
return((f(x+h) -f(x-h))/(2*h))
}
```

```{r}
fprime<- evalD(function(x) {x^3 + 2*x^2 +3},0:10)
```

```{r}
Df<-function(x){
return(3*x^2 + 4*x)
}
```
```{r}
plot(1:2, ylim =c(0,350), xlim=c(0,10), xlab ="x", ylab = "y'", type="n")
lines(0:10,fprime,col="blue",lwd=3)
lines(0:10,Df(0:10),col="red",lwd=2)
```

```{r}
Difference<-Df(0:10)-fprime
return(Difference)

plot(y=Difference, x=0:10,type="l") #The difference between the symbolic and finite-difference derviative is neglible, so it is a good approximation.

```

```{r} 
evalDh<- function(f,x,h){ #Adjusting EvalD to take h has an argument
return((f(x+h) -f(x-h))/(2*h))
}
```


```{r}
PlotDev<- function(){
plot(1:2, ylim =c(0,350), xlim=c(0,10), xlab ="x", ylab = "y'", type="n")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1),col="blue")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,0.1),col="green")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-5),col="orange")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-10),col="red")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-15),col="purple")
lines(0:10,evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-20),col="tomato")
}
```

```{r}
PlotDev()
```

```{r}
Difference2<-function(){
   diff1<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1)
   diff2<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,0.1)
   diff3<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-5)
   diff4<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-10)
   diff5<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1e-15)
   diff6<- Df(0:10) - evalDh(function(x) {x^3 + 2*x^2 +3},0:10,1-20)
return(list(hEquals1=c(diff1),hEquals0.1=c(diff2),hEquals5=c(diff3),hEquals10=c(diff4),hEquals10=c(diff5),hequals20=c(diff6))) #1e-5 is the best
  }
```
 

 Task 3 #This is incomplete
When $x=0$, 1e-8(abs(x)) will be 0.If $2*h$ is defined as 1e-8*abs(x) and $x = 0$, the numerator will be then divided by 0. As result, the derivative will be undefined.

When h is defined by 1e-8*pmax(1,abs(x)) and $x=0$, h will become 1. The derivative will then no longer be a undefined when x=0.

 Task 4
```{r}
myD <- function(f) {
    return(function(x) evalD(f, x))
}
```

#Example
```{r}
FirstDev <- myD(sin)
FirstDev(3.14/2) 

#Since this returns a value(which is equal to sin(3.14/2)), myD(sin) returns a function.

#myD "remembers" f only when the function has been assigned to a variable and then that variable will act as a function. 

#In the myD function we told the computer to return a function of x. The function, evalD(f,x), will then only accept a single numerical argument,x, and return the derivative at the point in the function,f.

```

```{r}
SecDev<- myD(myD(sin))
SecDev(3.14/2) #This should be approximately equal to -1.

ThirdDev<- myD(myD(myD(sin)))
ThirdDev(3.14/2) #This should be approximately 0, but approaches 0 from a negative value.

plot(1:2,xlim=c(0,10), ylim=c(-2,2), type='n')
lines(1:10,SecDev(1:10))
lines(1:10,ThirdDev(1:10))
```

```{r}
dddf<- D(sin(x) ~ x & x & x)
plot(1:2,xlim=c(0,10), ylim=c(-2,2), type='n')
lines(1:10, dddf(1:10))
```

```{r}
myD2<-function(f){
     h<- 1e-5
     return(function(x) {((f(x+h)-2*f(x)+f(x-h))/h^2)})
}
```

```{r}
SinD2<- myD2(sin)
SinD2(1.57)
```