

## Early Practice Ones
```{r}
CountsOdd<-function(x){
  Remainder<- vector(length=length(x))
  Remainder <- x%%2
  count <- sum(Remainder)
  return(count)
  }
```

Now we'll test it.  The answer should be 1:
```{r}
CountsOdd(c(3,4,2,4))
```

```{r}
CountEvens<- function(x){
 TotalCount<- length(x)
 Remainder<- vector(length=length(x))
 Remainder <- x%%2
 Oddcount <- sum(Remainder)
 Evencount<- TotalCount-Oddcount
 return(Evencount)}
 
 CountEvens<- function(x){
  x <- x+1
  Remainder<- vector(length=length(x))
Remainder <- x%%2
Evencount <- sum(Remainder)
return(Evencount)}

hypotenuseLength<- function(a,b) {
asquared <- a^2
bsquared <- b^2
hypotenusesquared <- asquared + bsquared
hypotenuse<- (hypotenusesquared)^(1/2)
return(hypotenuse)
}
```


```{r}
LawOfCosines<- function(a,b,theta){
asquared <- a^2
bsquared <- b^2
sum <- asquared + bsquared
Cosine <- cos(theta)
abCosine <- a %*% b %*% Cosine
TwoCosine <- 2 %*% abCosine
csquared <- sum - TwoCosine
c <- (csquared)^(1/2)
return(c)
}
```

Test statements:    
* Equalateral triangle.  Answer should be 10.

```{r}
LawOfCosines(10,10,pi/3)
```

```{r}
ThetaFromLengths<-function(a,b,c){
asqred <- a^2
bsqred <- b^2
csqred <- c^2
Sum <- asqred + bsqred - csqred
Divisor<- 2%*%a%*%b
quotient <- Sum/Divisor
angles <- acos(quotient)
return(angles)
}
```

Test again on an equilateral triangle: Angle should be $\pi/3$
```{r}
ThetaFromLengths(10,10,10)
pi/3
ThetaFromLengths(3,4,5)
pi/2
```

```{r}
testTriangles <- function(a=10,b=5,theta){
abs(ThetaFromLengths(a,b,LawOfCosines(a,b,theta) ) -theta) < 0.00001
}

```

Here are the test cases:
```{r}
testTriangles(a=100,theta=2.412)
```



