```{r}
ShowImage <- function(image){
 size <- dim(image) 
 canvas(x=c(1,size[2]), y=c(1,size[1]), asp=1) #The Column Number goes on the x axis, the row number goes on the y axis
 rasterImage(image,1,1,size[2],size[1]) # 1 and 1 represents where the plot starts on the row and column 
 } 
```

```{r}
ShowImage(puppy)
ShowImage(puppy[30:100,90:200,]) #The dog's head
ShowImage(puppy[160:198,1:40,]) #Left Paw
ShowImage(puppy[110:140,90:120,]) #Octagonal Dog Tag

red<-puppy[,,1]
pair<- cbind(red,red) #This combines the two red plane array's together by the column, creating double image.
ShowImage(pair)

framed <- cbind( red[,1:20], red, red[,197:216] ) #Borders the red with the two end columns of the red image
ShowImage(framed)

reverse <- cbind( red[,rev(1:20)], red, red[,rev(197:216)]) #Borders the image with the reverse of the  two end columns of the red images
ShowImage(reverse)

all4<- rbind(reverse[rev(1:20),],reverse,reverse[rev(179:198), ])  #Borders the reverse image with the two end rows of image

ShowImage(all4)
```

```{r}

ImagePlot<- function(image,width,mirrorimage=T){
  
  size<- dim(image)
    
  end2 <- size[2]-width+1
if (mirrorimage) { 
  framed<- cbind(image[,rev(1:width)], image, image[,rev(end2:size[2])])
  
  end<- size[1]-width+1
  
  framed2<- rbind(framed[rev(1:width),], framed, framed[rev(end:size[1]),])
  
  ShowImage(framed2)
  }
  else{
    framed<- cbind(image[,(1:width)], image, image[,(end2:size[2])])
  
  end<- size[1]-width+1
  
  framed2<- rbind(framed[(1:width),], framed, framed[(end:size[1]),])
  
  ShowImage(framed2)
  }
  
}
```

```{r}
Jamaica <- readJPEG(getURLContent("http://www.sandals.com/assets/img/sng/highlight-photo-01.jpg"))
ImagePlot(Jamaica[,,3],20,F)
```

```{r}
red   <- Jamaica[,,1]
green <- Jamaica[,,2]
blue  <- Jamaica[,,3]


weirdPuppy <- array( c(green,blue,red,alpha), dim=c(dim(red),3))
canvas( x=c(1,216), y=c(1,198), asp=1)
rasterImage(weirdPuppy,1,1,216,198)
```

```{r}

ColourFrame<- function(image,width,Neg=F,closetoRed=F){

size<- dim(image)

end2 <- size[2]-width+1

end<- size[1]-width+1

canvas(x=c(1,size[2]), y=c(1,size[1]), asp=1)

Array <-array(dim=c(2*width+size[1],2*width+size[2],3))

for (k in 1:3){
  picture<-image[,,k]
  if ((k!=1) & (closetoRed)){
    framed<- cbind(abs(as.numeric(Neg)-picture[,(1:width)])*0.4, picture, abs(as.numeric(Neg)-picture[,(end2:size[2])])*0.4)
  
  framed2<- rbind(abs(as.numeric(Neg)-framed[(1:width),])*0.4, framed, abs(as.numeric(Neg)-framed[(end:size[1]),])*0.4)
  }
  
  else{
  framed<- cbind(abs(as.numeric(Neg)-picture[,(1:width)]), picture, abs(as.numeric(Neg)-picture[,(end2:size[2])]))
  
  framed2<- rbind(abs(as.numeric(Neg)-framed[(1:width),]), framed, abs(as.numeric(Neg)-framed[(end:size[1]),]))

}
  
Array[,,k]<-framed2  
  }

rasterImage(Array,1,1,size[2],size[1])
}
``` 

```{r}
ColourFrame(Jamaica,50,F,T)
```

```{r}
ColourChoice<-function(colour,Array){
  
  res <-switch(colour, 
    
    red = function(Array){ 
 Array[,,2] <- Array[,,2]*0.4
 Array[,,3] <- Array[,,3]*0.4
 Array<- array(c(Array[,,1],Array[,,2],Array[,,3]), dim=c(dim(Array[,,1]),3))
  return(Array)}, 
          
          green = function(Array){
  Array[,,1] <- Array[,,1]*0.4
  Array[,,3] <- Array[,,3]*0.4
  Array<- array(c(Array[,,1],Array[,,2],Array[,,3]), dim=c(dim(Array[,,1]),3))
  return(Array)},
          
          blue =function(Array){
  Array[,,1] <- Array[,,1]*0.4
  Array[,,2] <- Array[,,3]*0.4
  Array<- array(c(Array[,,1],Array[,,2],Array[,,3]), dim=c(dim(Array[,,1]),3))
  return(Array)})
      }
```

```{r}

ColourCropFrame<- function(image,width,BW=F,closeto){
size<- dim(image)

end2 <- size[2]-width+1

end<- size[1]-width+1

canvas(x=c(1,size[2]), y=c(1,size[1]), asp=1)

Array <-array(dim=c(2*width+size[1],2*width+size[2],3))

for (k in 1:3){
  picture<-image[,,k]
    framed<- cbind(picture[,rev(1:width)], picture, picture[,rev(end2:size[2])])
  
    framed2<- rbind(framed[rev(1:width),], framed, framed[rev(end:size[1]),])

    Array[,,k]<-framed2
  }
  
if (!BW){  
Col<-ColourChoice(closeto,Array)
col<-Col(Array)
rasterImage(col,1,1,dim(col)[2],dim(col)[1])
      }else{
  BlackAndWhite<- round(Array[,,1])
  rasterImage(BlackAndWhite,1,1,size[2],size[1])
  }
}
```

```{r}
ColourCropFrame(Jamaica,20,F,"red")
```
